In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from config import tcr_embeddings_path, mhc_embeddings_path, peptide_embeddings_path, all_relations_path, train_path, val_path, test_path, CMV_dataset_path
import pickle
import dhg
from typing import List, Tuple, Optional, Union

/home/tarnickil/.conda/envs/mgr_thesis/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
with open(tcr_embeddings_path, "rb") as f:
    tcr_embbedings = pickle.load(f)

with open(mhc_embeddings_path, "rb") as f:
    mhc_embbedings = pickle.load(f)

with open(peptide_embeddings_path, "rb") as f:
    peptide_embbedings = pickle.load(f)
    
with open(all_relations_path, "rb") as f:
    all_relations = pickle.load(f)

with open(CMV_dataset_path, "rb") as f:
    cmv_dataset = pickle.load(f)

In [3]:
map_dict = {"Non-binding":0, "Binding":1}
all_relations["Binding"] = all_relations["Binding"].replace(map_dict)
tcr_embbedings.rename({"Name":"TCR_name"}, axis=1, inplace=True)

/tmp/ipykernel_566714/292328124.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  all_relations["Binding"] = all_relations["Binding"].replace(map_dict)

In [4]:
# all_relations.drop_duplicates(inplace=True)
# all_relations.reset_index(inplace=True, drop=True)
# all_relations[all_relations.duplicated() == True] # Pusty zbiór

# all_relations.drop(["index"], axis=1, inplace=True)
all_relations.drop(["Donor"], axis=1, inplace=True)
all_relations.drop(["TRAV", "TRAJ", "TRBV", "TRBD", "TRBJ"], axis=1, inplace=True)

kolumna_bin = 'Binding'
kolumna_count = "Count"
kolumna_klucza = 'Name'
pozostale = [col for col in all_relations.columns if col not in [kolumna_klucza, kolumna_bin, kolumna_count]]

# Zbuduj słownik agregacji dynamicznie
agg_dict = {col: (col, 'first') for col in pozostale}

# Dodaj kolumnę binarną
agg_dict[kolumna_bin] = (kolumna_bin, 'max')
agg_dict[kolumna_count] = (kolumna_count, 'max')

# Zastosuj
all_relations = all_relations.groupby(kolumna_klucza, as_index=False).agg(**agg_dict)

# all_relations.to_pickle(all_relations_path)
maska = all_relations.duplicated(subset=['Name'], keep=False)  # oznacza WSZYSTKIE wystąpienia
all_relations[maska].sort_values('Name')

Empty DataFrame
Columns: [Name, pMHC, CDR3a, CDR3b, Epitop, TCR_name, HLA_MHC, Binding, Count]
Index: []

In [5]:
all_relations

,Name,pMHC,CDR3a,CDR3b,Epitop,TCR_name,HLA_MHC,Binding,Count
0,A0101_SLEGGGLGY_NC_binder_TCR_1,A0101_SLEGGGLGY_NC_binder,CAVEALTGGGNKLTF,CASSAYTSGPKEQYF,NC_binder,TCR_1,HLA-A0101,0,1
1,A0101_SLEGGGLGY_NC_binder_TCR_10,A0101_SLEGGGLGY_NC_binder,CAVRDKNSGYSTLTF,CASTSADGYGYTF,NC_binder,TCR_10,HLA-A0101,0,1
2,A0101_SLEGGGLGY_NC_binder_TCR_100,A0101_SLEGGGLGY_NC_binder,CAVRDDDYKLSF,CASRFLAGGSHEQYF,NC_binder,TCR_100,HLA-A0101,0,4
3,A0101_SLEGGGLGY_NC_binder_TCR_1000,A0101_SLEGGGLGY_NC_binder,CAVRGYSSASKIIF,CASSHTEETGELFF,NC_binder,TCR_1000,HLA-A0101,0,1
4,A0101_SLEGGGLGY_NC_binder_TCR_10000,A0101_SLEGGGLGY_NC_binder,CALSDPLPLNAGKSTF,CASSERGGTVNEQFF,NC_binder,TCR_10000,HLA-A0101,0,1
...,...,...,...,...,...,...,...,...,...
3347845,NR(B0801)_AAKGRGAAL_NC_binder_TCR_9995,NR(B0801)_AAKGRGAAL_NC_binder,CALSLDNYGQNFVF,CASSETSLYEQYF,NC_binder,TCR_9995,HLA-B0801,0,1
3347846,NR(B0801)_AAKGRGAAL_NC_binder_TCR_9996,NR(B0801)_AAKGRGAAL_NC_binder,CALSPVNYGQNFVF,CASRDTDTQYF,NC_binder,TCR_9996,HLA-B0801,0,1
3347847,NR(B0801)_AAKGRGAAL_NC_binder_TCR_9997,NR(B0801)_AAKGRGAAL_NC_binder,CALSRIDNYGQNFVF,CASSQEVAGGIGDEQFF,NC_binder,TCR_9997,HLA-B0801,0,1
3347848,NR(B0801)_AAKGRGAAL_NC_binder_TCR_9998,NR(B0801)_AAKGRGAAL_NC_binder,CALSVDNYGQNFVF,CASSYSGTGGGLAGELFF,NC_binder,TCR_9998,HLA-B0801,0,1
3347849,NR(B0801)_AAKGRGAAL_NC_binder_TCR_9999,NR(B0801)_AAKGRGAAL_NC_binder,CAANTNAGKSTF,CASRRLATNEKLFF,NC_binder,TCR_9999,HLA-B0801,0,1

In [6]:
z = all_relations[["Epitop", "Binding"]].groupby(["Epitop"]).agg("sum")
z["count"] = all_relations[["Epitop", "Binding"]].groupby(["Epitop"]).agg("count").values
z["pct"] = z["Binding"]/z["count"]

In [7]:
CMV_dane_oczyszczone = all_relations[(all_relations["Epitop"] == "IE-1_CMV_binder") & (all_relations["HLA_MHC"].isin(["HLA-A0301","HLA-A2402"]))]
CMV_dane_oczyszczone.to_pickle(CMV_dataset_path)

In [8]:
t = cmv_dataset["Binding"].value_counts().values
t[1]/t[0]

np.float64(0.11587560829278049)

In [9]:
cmv_dataset

,Name,pMHC,CDR3a,CDR3b,Epitop,TCR_name,HLA_MHC,Binding,Count
2075667,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_1,A0301_KLGGALQAK_IE-1_CMV_binder,CAVEALTGGGNKLTF,CASSAYTSGPKEQYF,IE-1_CMV_binder,TCR_1,HLA-A0301,0,1
2075668,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_10,A0301_KLGGALQAK_IE-1_CMV_binder,CAVRDKNSGYSTLTF,CASTSADGYGYTF,IE-1_CMV_binder,TCR_10,HLA-A0301,0,1
2075669,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_100,A0301_KLGGALQAK_IE-1_CMV_binder,CAVRDDDYKLSF,CASRFLAGGSHEQYF,IE-1_CMV_binder,TCR_100,HLA-A0301,0,4
2075670,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_1000,A0301_KLGGALQAK_IE-1_CMV_binder,CAVRGYSSASKIIF,CASSHTEETGELFF,IE-1_CMV_binder,TCR_1000,HLA-A0301,0,1
2075671,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_10000,A0301_KLGGALQAK_IE-1_CMV_binder,CALSDPLPLNAGKSTF,CASSERGGTVNEQFF,IE-1_CMV_binder,TCR_10000,HLA-A0301,0,1
...,...,...,...,...,...,...,...,...,...
2477404,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9995,A2402_AYAQKIFKI_IE-1_CMV_binder,CALSLDNYGQNFVF,CASSETSLYEQYF,IE-1_CMV_binder,TCR_9995,HLA-A2402,0,1
2477405,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9996,A2402_AYAQKIFKI_IE-1_CMV_binder,CALSPVNYGQNFVF,CASRDTDTQYF,IE-1_CMV_binder,TCR_9996,HLA-A2402,0,1
2477406,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9997,A2402_AYAQKIFKI_IE-1_CMV_binder,CALSRIDNYGQNFVF,CASSQEVAGGIGDEQFF,IE-1_CMV_binder,TCR_9997,HLA-A2402,0,1
2477407,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9998,A2402_AYAQKIFKI_IE-1_CMV_binder,CALSVDNYGQNFVF,CASSYSGTGGGLAGELFF,IE-1_CMV_binder,TCR_9998,HLA-A2402,0,1
2477408,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9999,A2402_AYAQKIFKI_IE-1_CMV_binder,CAANTNAGKSTF,CASRRLATNEKLFF,IE-1_CMV_binder,TCR_9999,HLA-A2402,0,1

In [10]:
Data_all = cmv_dataset[['Name', 'TCR_name', 'HLA_MHC', 'Epitop']]
Data = Data_all.copy()
len(Data['TCR_name'].value_counts().index)

66957

In [11]:
nrow = Data.shape[0]
test_nrow = np.round(nrow*0.2, 0)
val_nrow = np.round(nrow*0.2, 0)
TCRs = np.unique(Data["TCR_name"].values)
rng = np.random.default_rng(seed=42)
test_tcr = np.array([])
val_tcr = np.array([])

while test_nrow >= 0:
    tcr_i = rng.choice(TCRs, size=100)
    print(tcr_i)
    val = np.sum(Data['TCR_name'][Data["TCR_name"].isin(tcr_i)].value_counts().values)
    test_nrow -= val
    test_tcr = np.append(test_tcr, tcr_i)
test_tcr.ravel()

Data = Data[~Data["TCR_name"].isin(test_tcr)]
TCRs = np.unique(Data["TCR_name"].values)
while val_nrow >= 0:
    tcr_i = rng.choice(TCRs, size=100)
    print(tcr_i)
    val = np.sum(Data['TCR_name'][Data["TCR_name"].isin(tcr_i)].value_counts().values)
    val_nrow -= val
    val_tcr = np.append(val_tcr, tcr_i)
val_tcr.ravel()

['TCR_15376' 'TCR_56638' 'TCR_49444' 'TCR_36445' 'TCR_36092' 'TCR_61739'
 'TCR_15177' 'TCR_52021' 'TCR_22138' 'TCR_15673' 'TCR_41724' 'TCR_8529'
 'TCR_54335' 'TCR_55866' 'TCR_53234' 'TCR_57368' 'TCR_40926' 'TCR_17719'
 'TCR_60602' 'TCR_37139' 'TCR_4015' 'TCR_32342' 'TCR_20999' 'TCR_65847'
 'TCR_57097' 'TCR_488' 'TCR_34248' 'TCR_5958' 'TCR_42867' 'TCR_36719'
 'TCR_37143' 'TCR_23692' 'TCR_15550' 'TCR_43418' 'TCR_63503' 'TCR_13844'
 'TCR_6172' 'TCR_59873' 'TCR_26676' 'TCR_48063' 'TCR_19956' 'TCR_55682'
 'TCR_52211' 'TCR_31361' 'TCR_14090' 'TCR_8232' 'TCR_36856' 'TCR_63819'
 'TCR_50850' 'TCR_56905' 'TCR_55791' 'TCR_21727' 'TCR_31928' 'TCR_38123'
 'TCR_39997' 'TCR_12637' 'TCR_42935' 'TCR_19296' 'TCR_54796' 'TCR_51159'
 'TCR_65591' 'TCR_5488' 'TCR_32092' 'TCR_804' 'TCR_34757' 'TCR_29633'
 'TCR_64567' 'TCR_32321' 'TCR_14599' 'TCR_38295' 'TCR_57948' 'TCR_21415'
 'TCR_37897' 'TCR_17828' 'TCR_51366' 'TCR_38665' 'TCR_29897' 'TCR_23672'
 'TCR_44015' 'TCR_50361' 'TCR_66663' 'TCR_36341' 'TCR_19682' 'TCR_60176'
 'TCR_4795' 'TCR_52197' 'TCR_15858' 'TCR_28822' 'TCR_5627' 'TCR_60150'
 'TCR_36224' 'TCR_58495' 'TCR_6072' 'TCR_33348' 'TCR_64118' 'TCR_27373'
 'TCR_24434' 'TCR_51125' 'TCR_48370' 'TCR_1842']
['TCR_6018' 'TCR_22044' 'TCR_58502' 'TCR_10440' 'TCR_58017' 'TCR_5742'
 'TCR_57023' 'TCR_50062' 'TCR_38415' 'TCR_52492' 'TCR_26699' 'TCR_57046'
 'TCR_43482' 'TCR_37653' 'TCR_40466' 'TCR_44271' 'TCR_12242' 'TCR_18422'
 'TCR_24791' 'TCR_1690' 'TCR_36490' 'TCR_50277' 'TCR_49435' 'TCR_38388'
 'TCR_61526' 'TCR_4406' 'TCR_14770' 'TCR_56099' 'TCR_44624' 'TCR_48247'
 'TCR_44068' 'TCR_43358' 'TCR_15456' 'TCR_43697' 'TCR_57900' 'TCR_28314'
 'TCR_46326' 'TCR_11855' 'TCR_30939' 'TCR_36315' 'TCR_8959' 'TCR_22929'
 'TCR_26663' 'TCR_34616' 'TCR_9556' 'TCR_61425' 'TCR_12088' 'TCR_24095'
 'TCR_59513' 'TCR_13510' 'TCR_61562' 'TCR_26955' 'TCR_65298' 'TCR_27691'
 'TCR_36170' 'TCR_49887' 'TCR_17608' 'TCR_43566' 'TCR_40430' 'TCR_57237'
 'TCR_9764' 'TCR_5003' 'TCR_34656' 'TCR_34488' 'TCR_35185' 'TCR_59052'
 'TCR_29355' 'TCR_2006' 'TCR_30142' 'TCR_11366' 'TCR_16394' 'TCR_15424'
 'TCR_56493' 'TCR_53529' 'TCR_51987' 'TCR_37831' 'TCR_53209' 'TCR_19717'
 'TCR_64270' 'TCR_40191' 'TCR_66527' 'TCR_19177' 'TCR_39969' 'TCR_5196'
 'TCR_39866' 'TCR_36885' 'TCR_20013' 'TCR_3296' 'TCR_24387' 'TCR_28168'
 'TCR_51199' 'TCR_47980' 'TCR_4659' 'TCR_31800' 'TCR_757' 'TCR_1528'
 'TCR_30642' 'TCR_17109' 'TCR_30422' 'TCR_7701']
['TCR_32069' 'TCR_64750' 'TCR_39832' 'TCR_52163' 'TCR_37563' 'TCR_26019'
 'TCR_56051' 'TCR_8140' 'TCR_25879' 'TCR_56927' 'TCR_25735' 'TCR_53199'
 'TCR_57545' 'TCR_37077' 'TCR_54405' 'TCR_26403' 'TCR_14774' 'TCR_15807'
 'TCR_36937' 'TCR_64390' 'TCR_17687' 'TCR_37464' 'TCR_52423' 'TCR_22192'
 'TCR_53484' 'TCR_28435' 'TCR_5873' 'TCR_44902' 'TCR_42956' 'TCR_20650'
 'TCR_37911' 'TCR_61619' 'TCR_11174' 'TCR_55708' 'TCR_39693' 'TCR_53354'
 'TCR_49970' 'TCR_36036' 'TCR_286' 'TCR_47800' 'TCR_18448' 'TCR_45197'
 'TCR_15704' 'TCR_49159' 'TCR_47888' 'TCR_15087' 'TCR_55646' 'TCR_35055'
 'TCR_57417' 'TCR_12505' 'TCR_20811' 'TCR_39768' 'TCR_2134' 'TCR_29877'
 'TCR_49807' 'TCR_18707' 'TCR_50837' 'TCR_16229' 'TCR_20554' 'TCR_4541'
 'TCR_57815' 'TCR_20278' 'TCR_28076' 'TCR_65748' 'TCR_9377' 'TCR_45013'
 'TCR_36938' 'TCR_30900' 'TCR_46905' 'TCR_45607' 'TCR_27760' 'TCR_11371'
 'TCR_19127' 'TCR_7500' 'TCR_35197' 'TCR_39062' 'TCR_38147' 'TCR_57167'
 'TCR_13912' 'TCR_14984' 'TCR_26620' 'TCR_39325' 'TCR_50440' 'TCR_3957'
 'TCR_36584' 'TCR_66513' 'TCR_19701' 'TCR_44451' 'TCR_42675' 'TCR_38531'
 'TCR_58666' 'TCR_26086' 'TCR_7211' 'TCR_2998' 'TCR_42840' 'TCR_41374'
 'TCR_61206' 'TCR_36448' 'TCR_27146' 'TCR_1130']
['TCR_31913' 'TCR_59793' 'TCR_10595' 'TCR_64001' 'TCR_4271' 'TCR_1845'
 'TCR_28208' 'TCR_43385' 'TCR_29021' 'TCR_16540' 'TCR_50130' 'TCR_50508'
 'TCR_17161' 'TCR_26946' 'TCR_24695' 'TCR_49736' 'TCR_54006' 'TCR_53808'
 'TCR_6657' 'TCR_56318' 'TCR_29322' 'TCR_16491' 'TCR_47037' 'TCR_65199'
 'TCR_8500' 'TCR_23871' 'TCR_24247' 'TCR_12252' 'TCR_18510' 'TCR_43434'
 'TCR_4295' 'TCR_3235' 'TCR_28677' 'TCR_60001' 'TCR_37720' 'TCR_58705'
 'TCR_7781' 'TCR_29109' 'TCR_22214' 'TCR_716' 'TCR_48254' 'TCR_27529'
 'TCR_47472' 'TCR_41035' 'TCR_64567' 'TCR_25422' 'TCR_948' 'TCR_66405'
 'TCR_20888' 'TCR_19918' 'TCR_42126' 'TCR_12704' 'TCR_28003' 'TCR_36217'
 'TCR_8152' 'TCR_9539' 'TCR_1913' 'TCR_63732' 'TCR_15478' 'TCR_5511'
 'TCR_60958' 'TCR_63679' 'TCR_23461' 'TCR_63839' 'TCR_16988' 'TCR_41265'
 'TCR_38294' 'TCR_29036' 'TCR_1133' 'TCR_56520' 'TCR_3022' 'TCR_49871'
 'TCR_34719' 'TCR_32515' 'TCR_63407' 'TCR_15691' 'TCR_54388' 'TCR_5500'
 'TCR_32898' 'TCR_25814' 'TCR_10317' 'TCR_66452' 'TCR_6849' 'TCR_24519'
 'TCR_11920' 'TCR_17396' 'TCR_14074' 'TCR_60081' 'TCR_63746' 'TCR_19235'
 'TCR_54999' 'TCR_20800' 'TCR_32126' 'TCR_46117' 'TCR_53382' 'TCR_62700'
 'TCR_12697' 'TCR_21835' 'TCR_26902' 'TCR_287']
['TCR_988' 'TCR_56846' 'TCR_29307' 'TCR_830' 'TCR_40087' 'TCR_40173'
 'TCR_36133' 'TCR_1867' 'TCR_66304' 'TCR_10838' 'TCR_2050' 'TCR_23838'
 'TCR_26829' 'TCR_17942' 'TCR_1108' 'TCR_50834' 'TCR_8149' 'TCR_1734'
 'TCR_27869' 'TCR_4051' 'TCR_65891' 'TCR_51835' 'TCR_5617' 'TCR_45016'
 'TCR_35129' 'TCR_22036' 'TCR_62082' 'TCR_58456' 'TCR_1151' 'TCR_53109'
 'TCR_15083' 'TCR_54530' 'TCR_59772' 'TCR_17897' 'TCR_36141' 'TCR_17456'
 'TCR_44183' 'TCR_65895' 'TCR_14871' 'TCR_33957' 'TCR_8379' 'TCR_28133'
 'TCR_17966' 'TCR_39441' 'TCR_40633' 'TCR_49944' 'TCR_28904' 'TCR_7323'
 'TCR_41396' 'TCR_2726' 'TCR_7604' 'TCR_65729' 'TCR_40078' 'TCR_11496'
 'TCR_45971' 'TCR_43455' 'TCR_1893' 'TCR_48202' 'TCR_60666' 'TCR_1638'
 'TCR_53587' 'TCR_18455' 'TCR_55123' 'TCR_35254' 'TCR_1039' 'TCR_7963'
 'TCR_20' 'TCR_45917' 'TCR_20933' 'TCR_66223' 'TCR_54491' 'TCR_58470'
 'TCR_36035' 'TCR_38163' 'TCR_48221' 'TCR_5729' 'TCR_61038' 'TCR_11072'
 'TCR_49987' 'TCR_16575' 'TCR_2735' 'TCR_59982' 'TCR_25094' 'TCR_58015'
 'TCR_3790' 'TCR_24016' 'TCR_30139' 'TCR_41983' 'TCR_56106' 'TCR_46518'
 'TCR_66235' 'TCR_6229' 'TCR_55397' 'TCR_46342' 'TCR_27465' 'TCR_34860'
 'TCR_17162' 'TCR_32547' 'TCR_65829' 'TCR_35662']
['TCR_16851' 'TCR_49285' 'TCR_7745' 'TCR_62274' 'TCR_26514' 'TCR_37350'
 'TCR_41999' 'TCR_24933' 'TCR_2619' 'TCR_2426' 'TCR_9672' 'TCR_54954'
 'TCR_6067' 'TCR_59205' 'TCR_7536' 'TCR_16342' 'TCR_63126' 'TCR_14008'
 'TCR_38648' 'TCR_4582' 'TCR_31563' 'TCR_18807' 'TCR_21586' 'TCR_59695'
 'TCR_29204' 'TCR_2870' 'TCR_65641' 'TCR_18669' 'TCR_65153' 'TCR_65498'
 'TCR_46068' 'TCR_19974' 'TCR_19390' 'TCR_27156' 'TCR_44795' 'TCR_19255'
 'TCR_37457' 'TCR_16958' 'TCR_42556' 'TCR_11272' 'TCR_52725' 'TCR_13336'
 'TCR_21738' 'TCR_20521' 'TCR_60074' 'TCR_13214' 'TCR_35866' 'TCR_45621'
 'TCR_41092' 'TCR_51018' 'TCR_58395' 'TCR_33719' 'TCR_59908' 'TCR_29160'
 'TCR_9059' 'TCR_40400' 'TCR_54351' 'TCR_62727' 'TCR_57765' 'TCR_61289'
 'TCR_42329' 'TCR_12617' 'TCR_39712' 'TCR_20935' 'TCR_63578' 'TCR_24264'
 'TCR_23741' 'TCR_25026' 'TCR_48720' 'TCR_44421' 'TCR_6915' 'TCR_35082'
 'TCR_27008' 'TCR_12966' 'TCR_10423' 'TCR_32512' 'TCR_6579' 'TCR_4156'
 'TCR_63845' 'TCR_16124' 'TCR_15621' 'TCR_60222' 'TCR_16430' 'TCR_13129'
 'TCR_34349' 'TCR_65730' 'TCR_51541' 'TCR_15971' 'TCR_60444' 'TCR_60833'
 'TCR_5825' 'TCR_64393' 'TCR_24453' 'TCR_8768' 'TCR_29323' 'TCR_5833'
 'TCR_44911' 'TCR_56971' 'TCR_47831' 'TCR_48715']
['TCR_47136' 'TCR_56942' 'TCR_54534' 'TCR_18106' 'TCR_59779' 'TCR_42301'
 'TCR_29468' 'TCR_40986' 'TCR_8008' 'TCR_61677' 'TCR_60237' 'TCR_37888'
 'TCR_57251' 'TCR_33203' 'TCR_51347' 'TCR_4854' 'TCR_25050' 'TCR_26055'
 'TCR_13682' 'TCR_18420' 'TCR_36128' 'TCR_38797' 'TCR_19949' 'TCR_3512'
 'TCR_46406' 'TCR_24012' 'TCR_30380' 'TCR_32144' 'TCR_40432' 'TCR_32077'
 'TCR_54407' 'TCR_29734' 'TCR_36145' 'TCR_32865' 'TCR_2102' 'TCR_51321'
 'TCR_24186' 'TCR_27889' 'TCR_57771' 'TCR_6916' 'TCR_50423' 'TCR_65218'
 'TCR_61473' 'TCR_3898' 'TCR_56417' 'TCR_29787' 'TCR_37749' 'TCR_42264'
 'TCR_7617' 'TCR_61133' 'TCR_39481' 'TCR_49324' 'TCR_22192' 'TCR_58472'
 'TCR_43324' 'TCR_4210' 'TCR_56176' 'TCR_48139' 'TCR_14365' 'TCR_27363'
 'TCR_20647' 'TCR_54284' 'TCR_12115' 'TCR_22195' 'TCR_46000' 'TCR_51868'
 'TCR_40327' 'TCR_61867' 'TCR_65375' 'TCR_1796' 'TCR_7136' 'TCR_47021'
 'TCR_48338' 'TCR_15729' 'TCR_47473' 'TCR_53730' 'TCR_44999' 'TCR_1509'
 'TCR_41528' 'TCR_664' 'TCR_53592' 'TCR_18279' 'TCR_7584' 'TCR_752'
 'TCR_20205' 'TCR_58260' 'TCR_34507' 'TCR_45775' 'TCR_36826' 'TCR_57160'
 'TCR_9798' 'TCR_57913' 'TCR_66123' 'TCR_6746' 'TCR_15428' 'TCR_25267'
 'TCR_53499' 'TCR_45557' 'TCR_13019' 'TCR_15726']
['TCR_41367' 'TCR_47129' 'TCR_20103' 'TCR_2032' 'TCR_17793' 'TCR_44042'
 'TCR_10470' 'TCR_44494' 'TCR_38679' 'TCR_38079' 'TCR_50932' 'TCR_41492'
 'TCR_53853' 'TCR_56033' 'TCR_65446' 'TCR_58162' 'TCR_41196' 'TCR_39657'
 'TCR_24201' 'TCR_4613' 'TCR_18383' 'TCR_66115' 'TCR_60921' 'TCR_17213'
 'TCR_57361' 'TCR_17054' 'TCR_53460' 'TCR_15283' 'TCR_39417' 'TCR_49642'
 'TCR_53917' 'TCR_35223' 'TCR_65537' 'TCR_56660' 'TCR_22548' 'TCR_50447'
 'TCR_54020' 'TCR_30102' 'TCR_54485' 'TCR_64134' 'TCR_59239' 'TCR_5595'
 'TCR_48234' 'TCR_26300' 'TCR_5792' 'TCR_31945' 'TCR_42069' 'TCR_28947'
 'TCR_28861' 'TCR_19497' 'TCR_7666' 'TCR_18904' 'TCR_15196' 'TCR_66410'
 'TCR_43444' 'TCR_36387' 'TCR_54440' 'TCR_33097' 'TCR_17707' 'TCR_53970'
 'TCR_20603' 'TCR_43321' 'TCR_6929' 'TCR_66411' 'TCR_31739' 'TCR_5702'
 'TCR_46919' 'TCR_38887' 'TCR_18430' 'TCR_32678' 'TCR_49284' 'TCR_9192'
 'TCR_10292' 'TCR_53251' 'TCR_610' 'TCR_7057' 'TCR_35537' 'TCR_17137'
 'TCR_26327' 'TCR_61252' 'TCR_62903' 'TCR_4839' 'TCR_17395' 'TCR_17345'
 'TCR_38813' 'TCR_45447' 'TCR_11949' 'TCR_51342' 'TCR_42810' 'TCR_10739'
 'TCR_15764' 'TCR_37376' 'TCR_53542' 'TCR_59739' 'TCR_3599' 'TCR_27798'
 'TCR_8089' 'TCR_37631' 'TCR_29003' 'TCR_36653']
['TCR_10726' 'TCR_28193' 'TCR_41065' 'TCR_65345' 'TCR_54485' 'TCR_57080'
 'TCR_42834' 'TCR_16662' 'TCR_33556' 'TCR_982' 'TCR_1266' 'TCR_62980'
 'TCR_51246' 'TCR_27106' 'TCR_56881' 'TCR_60430' 'TCR_12601' 'TCR_16410'
 'TCR_50116' 'TCR_9945' 'TCR_11441' 'TCR_50112' 'TCR_18225' 'TCR_49176'
 'TCR_47560' 'TCR_15448' 'TCR_51019' 'TCR_64054' 'TCR_6203' 'TCR_11745'
 'TCR_24817' 'TCR_24510' 'TCR_37314' 'TCR_18617' 'TCR_61482' 'TCR_56808'
 'TCR_58710' 'TCR_21942' 'TCR_10876' 'TCR_64875' 'TCR_27408' 'TCR_49546'
 'TCR_64802' 'TCR_12177' 'TCR_10327' 'TCR_10324' 'TCR_19419' 'TCR_1311'
 'TCR_59411' 'TCR_46511' 'TCR_8796' 'TCR_58297' 'TCR_7780' 'TCR_24373'
 'TCR_27341' 'TCR_61184' 'TCR_24755' 'TCR_13447' 'TCR_5032' 'TCR_58266'
 'TCR_8081' 'TCR_65909' 'TCR_17243' 'TCR_56527' 'TCR_60988' 'TCR_52068'
 'TCR_59400' 'TCR_60496' 'TCR_36908' 'TCR_12417' 'TCR_3749' 'TCR_22157'
 'TCR_16851' 'TCR_17526' 'TCR_52022' 'TCR_40400' 'TCR_42529' 'TCR_54904'
 'TCR_43037' 'TCR_47964' 'TCR_15181' 'TCR_61289' 'TCR_37042' 'TCR_19351'
 'TCR_59010' 'TCR_54268' 'TCR_13193' 'TCR_21630' 'TCR_10947' 'TCR_26314'
 'TCR_16022' 'TCR_52779' 'TCR_41488' 'TCR_8805' 'TCR_5516' 'TCR_46851'
 'TCR_40690' 'TCR_13282' 'TCR_14228' 'TCR_47138']
['TCR_10261' 'TCR_1255' 'TCR_23202' 'TCR_63278' 'TCR_37654' 'TCR_52759'
 'TCR_348' 'TCR_20430' 'TCR_32364' 'TCR_15525' 'TCR_56414' 'TCR_21057'
 'TCR_3268' 'TCR_8795' 'TCR_45671' 'TCR_37631' 'TCR_42720' 'TCR_57248'
 'TCR_25333' 'TCR_48349' 'TCR_62588' 'TCR_44493' 'TCR_36907' 'TCR_18744'
 'TCR_24960' 'TCR_6745' 'TCR_42615' 'TCR_28157' 'TCR_35209' 'TCR_44830'
 'TCR_42391' 'TCR_52167' 'TCR_25514' 'TCR_49121' 'TCR_36675' 'TCR_66680'
 'TCR_19515' 'TCR_18944' 'TCR_37819' 'TCR_40631' 'TCR_51630' 'TCR_34345'
 'TCR_6506' 'TCR_38572' 'TCR_17792' 'TCR_17182' 'TCR_8396' 'TCR_18079'
 'TCR_6856' 'TCR_26756' 'TCR_15627' 'TCR_28360' 'TCR_47040' 'TCR_35785'
 'TCR_57339' 'TCR_46817' 'TCR_3415' 'TCR_48241' 'TCR_8279' 'TCR_34814'
 'TCR_19245' 'TCR_34631' 'TCR_60624' 'TCR_23111' 'TCR_6933' 'TCR_45450'
 'TCR_4625' 'TCR_29103' 'TCR_65467' 'TCR_12170' 'TCR_27998' 'TCR_35210'
 'TCR_3876' 'TCR_38570' 'TCR_18912' 'TCR_23593' 'TCR_15738' 'TCR_44496'
 'TCR_31141' 'TCR_44092' 'TCR_45535' 'TCR_52300' 'TCR_42963' 'TCR_49044'
 'TCR_45380' 'TCR_49314' 'TCR_47158' 'TCR_29053' 'TCR_2484' 'TCR_57450'
 'TCR_3065' 'TCR_43090' 'TCR_21868' 'TCR_35997' 'TCR_41916' 'TCR_47722'
 'TCR_41718' 'TCR_31731' 'TCR_7695' 'TCR_40897']
['TCR_58708' 'TCR_54393' 'TCR_43643' 'TCR_63413' 'TCR_17728' 'TCR_65502'
 'TCR_61233' 'TCR_40347' 'TCR_54193' 'TCR_41350' 'TCR_26194' 'TCR_582'
 'TCR_24818' 'TCR_28948' 'TCR_41291' 'TCR_6046' 'TCR_33133' 'TCR_39777'
 'TCR_12508' 'TCR_16980' 'TCR_1337' 'TCR_1434' 'TCR_62336' 'TCR_60738'
 'TCR_59527' 'TCR_13346' 'TCR_14677' 'TCR_26908' 'TCR_44063' 'TCR_30132'
 'TCR_3938' 'TCR_20422' 'TCR_54035' 'TCR_28914' 'TCR_14007' 'TCR_54754'
 'TCR_64401' 'TCR_10883' 'TCR_36312' 'TCR_59846' 'TCR_52552' 'TCR_61614'
 'TCR_35019' 'TCR_32430' 'TCR_52734' 'TCR_19255' 'TCR_24425' 'TCR_46205'
 'TCR_5028' 'TCR_17209' 'TCR_40629' 'TCR_31989' 'TCR_40233' 'TCR_7493'
 'TCR_14614' 'TCR_9725' 'TCR_37090' 'TCR_56526' 'TCR_35578' 'TCR_28738'
 'TCR_56436' 'TCR_51437' 'TCR_1868' 'TCR_52506' 'TCR_5538' 'TCR_3337'
 'TCR_6578' 'TCR_48619' 'TCR_30101' 'TCR_10644' 'TCR_50672' 'TCR_22596'
 'TCR_55588' 'TCR_41640' 'TCR_38123' 'TCR_19867' 'TCR_52875' 'TCR_19997'
 'TCR_35172' 'TCR_60395' 'TCR_65460' 'TCR_9343' 'TCR_7468' 'TCR_43501'
 'TCR_22079' 'TCR_60561' 'TCR_58305' 'TCR_9414' 'TCR_49225' 'TCR_18530'
 'TCR_40302' 'TCR_3701' 'TCR_60796' 'TCR_33655' 'TCR_2980' 'TCR_14821'
 'TCR_60343' 'TCR_55515' 'TCR_12482' 'TCR_36138']
['TCR_38907' 'TCR_38280' 'TCR_65374' 'TCR_19078' 'TCR_28459' 'TCR_20900'
 'TCR_24707' 'TCR_64661' 'TCR_66688' 'TCR_12689' 'TCR_48089' 'TCR_2403'
 'TCR_21601' 'TCR_27599' 'TCR_21711' 'TCR_39539' 'TCR_9734' 'TCR_45338'
 'TCR_53582' 'TCR_39725' 'TCR_10836' 'TCR_15067' 'TCR_2620' 'TCR_24682'
 'TCR_60652' 'TCR_60834' 'TCR_61469' 'TCR_48420' 'TCR_43513' 'TCR_49117'
 'TCR_34512' 'TCR_50385' 'TCR_57873' 'TCR_55972' 'TCR_4699' 'TCR_135'
 'TCR_53685' 'TCR_3209' 'TCR_54812' 'TCR_42510' 'TCR_631' 'TCR_30394'
 'TCR_66125' 'TCR_60888' 'TCR_29951' 'TCR_39079' 'TCR_42017' 'TCR_56316'
 'TCR_51527' 'TCR_61341' 'TCR_32287' 'TCR_40417' 'TCR_35963' 'TCR_64809'
 'TCR_28377' 'TCR_4538' 'TCR_17239' 'TCR_61236' 'TCR_33151' 'TCR_30521'
 'TCR_45125' 'TCR_40057' 'TCR_61098' 'TCR_42020' 'TCR_41152' 'TCR_16324'
 'TCR_11319' 'TCR_34014' 'TCR_9890' 'TCR_65279' 'TCR_47901' 'TCR_48012'
 'TCR_33590' 'TCR_20695' 'TCR_10512' 'TCR_30417' 'TCR_29069' 'TCR_21544'
 'TCR_25616' 'TCR_11494' 'TCR_46635' 'TCR_65889' 'TCR_51626' 'TCR_37007'
 'TCR_35323' 'TCR_28530' 'TCR_18580' 'TCR_46063' 'TCR_44137' 'TCR_10438'
 'TCR_35038' 'TCR_26752' 'TCR_20259' 'TCR_52364' 'TCR_41685' 'TCR_48190'
 'TCR_52994' 'TCR_8901' 'TCR_58374' 'TCR_47382']
['TCR_6297' 'TCR_38774' 'TCR_9080' 'TCR_55884' 'TCR_49221' 'TCR_64434'
 'TCR_41037' 'TCR_53428' 'TCR_27156' 'TCR_7781' 'TCR_47563' 'TCR_57122'
 'TCR_37763' 'TCR_62232' 'TCR_14468' 'TCR_16875' 'TCR_40557' 'TCR_54134'
 'TCR_58763' 'TCR_36519' 'TCR_49149' 'TCR_43329' 'TCR_768' 'TCR_49415'
 'TCR_35117' 'TCR_8179' 'TCR_16461' 'TCR_9069' 'TCR_1928' 'TCR_27367'
 'TCR_59501' 'TCR_54214' 'TCR_8211' 'TCR_55193' 'TCR_48386' 'TCR_30879'
 'TCR_10281' 'TCR_17462' 'TCR_27943' 'TCR_12465' 'TCR_40621' 'TCR_56842'
 'TCR_7784' 'TCR_39508' 'TCR_62727' 'TCR_9126' 'TCR_61812' 'TCR_38018'
 'TCR_296' 'TCR_8668' 'TCR_24576' 'TCR_3480' 'TCR_14459' 'TCR_57827'
 'TCR_49159' 'TCR_15109' 'TCR_23371' 'TCR_43471' 'TCR_42564' 'TCR_58331'
 'TCR_26033' 'TCR_65722' 'TCR_36783' 'TCR_59569' 'TCR_24363' 'TCR_12225'
 'TCR_13315' 'TCR_32458' 'TCR_7175' 'TCR_12932' 'TCR_32232' 'TCR_16584'
 'TCR_66135' 'TCR_50693' 'TCR_5596' 'TCR_52980' 'TCR_49592' 'TCR_56624'
 'TCR_10488' 'TCR_62151' 'TCR_54584' 'TCR_54558' 'TCR_33707' 'TCR_5826'
 'TCR_33006' 'TCR_12949' 'TCR_64704' 'TCR_24130' 'TCR_16138' 'TCR_47475'
 'TCR_24078' 'TCR_6171' 'TCR_3674' 'TCR_10269' 'TCR_7089' 'TCR_4101'
 'TCR_25846' 'TCR_50812' 'TCR_41974' 'TCR_11782']
['TCR_55776' 'TCR_34184' 'TCR_5217' 'TCR_63971' 'TCR_46795' 'TCR_50470'
 'TCR_25343' 'TCR_24319' 'TCR_35006' 'TCR_61388' 'TCR_41587' 'TCR_30971'
 'TCR_5698' 'TCR_61421' 'TCR_64386' 'TCR_28012' 'TCR_52762' 'TCR_45572'
 'TCR_37053' 'TCR_33918' 'TCR_16901' 'TCR_2656' 'TCR_43120' 'TCR_63423'
 'TCR_62204' 'TCR_21301' 'TCR_50935' 'TCR_15108' 'TCR_50675' 'TCR_30602'
 'TCR_37106' 'TCR_53243' 'TCR_35602' 'TCR_58656' 'TCR_42151' 'TCR_9922'
 'TCR_4846' 'TCR_27858' 'TCR_56718' 'TCR_34581' 'TCR_42188' 'TCR_18243'
 'TCR_1719' 'TCR_44640' 'TCR_21248' 'TCR_9852' 'TCR_61562' 'TCR_52233'
 'TCR_54272' 'TCR_45867' 'TCR_13630' 'TCR_33642' 'TCR_39877' 'TCR_65155'
 'TCR_23224' 'TCR_39944' 'TCR_30731' 'TCR_18095' 'TCR_16205' 'TCR_32015'
 'TCR_14965' 'TCR_14045' 'TCR_31141' 'TCR_22169' 'TCR_43431' 'TCR_11062'
 'TCR_28186' 'TCR_37313' 'TCR_7778' 'TCR_48236' 'TCR_63071' 'TCR_30685'
 'TCR_37099' 'TCR_35330' 'TCR_63474' 'TCR_754' 'TCR_7729' 'TCR_55312'
 'TCR_40315' 'TCR_42591' 'TCR_8824' 'TCR_27145' 'TCR_30891' 'TCR_64052'
 'TCR_33278' 'TCR_24165' 'TCR_43773' 'TCR_29603' 'TCR_63684' 'TCR_64780'
 'TCR_28439' 'TCR_41909' 'TCR_9033' 'TCR_54731' 'TCR_22992' 'TCR_45598'
 'TCR_47354' 'TCR_49376' 'TCR_11504' 'TCR_28039']
['TCR_61499' 'TCR_24543' 'TCR_28058' 'TCR_29432' 'TCR_20688' 'TCR_19365'
 'TCR_3091' 'TCR_62686' 'TCR_1009' 'TCR_27067' 'TCR_13651' 'TCR_43834'
 'TCR_251' 'TCR_57724' 'TCR_45251' 'TCR_57232' 'TCR_48259' 'TCR_36416'
 'TCR_61881' 'TCR_38699' 'TCR_6981' 'TCR_968' 'TCR_45494' 'TCR_50650'
 'TCR_25404' 'TCR_5909' 'TCR_50469' 'TCR_64388' 'TCR_26089' 'TCR_5746'
 'TCR_38338' 'TCR_21157' 'TCR_20313' 'TCR_43876' 'TCR_29249' 'TCR_16138'
 'TCR_35739' 'TCR_49344' 'TCR_29218' 'TCR_7307' 'TCR_56976' 'TCR_40897'
 'TCR_66321' 'TCR_3609' 'TCR_18414' 'TCR_12157' 'TCR_66525' 'TCR_7574'
 'TCR_54546' 'TCR_16204' 'TCR_27694' 'TCR_12473' 'TCR_13086' 'TCR_24826'
 'TCR_44476' 'TCR_13947' 'TCR_907' 'TCR_37424' 'TCR_25899' 'TCR_41098'
 'TCR_57614' 'TCR_28834' 'TCR_12861' 'TCR_13069' 'TCR_6134' 'TCR_16723'
 'TCR_48299' 'TCR_33169' 'TCR_56853' 'TCR_13645' 'TCR_6410' 'TCR_52071'
 'TCR_37072' 'TCR_22473' 'TCR_8620' 'TCR_28200' 'TCR_39558' 'TCR_33749'
 'TCR_23891' 'TCR_35102' 'TCR_19126' 'TCR_10098' 'TCR_27474' 'TCR_16751'
 'TCR_34994' 'TCR_61990' 'TCR_19796' 'TCR_10071' 'TCR_16693' 'TCR_40620'
 'TCR_26560' 'TCR_39497' 'TCR_11760' 'TCR_3007' 'TCR_34713' 'TCR_35991'
 'TCR_43210' 'TCR_57037' 'TCR_38154' 'TCR_60690']
['TCR_41920' 'TCR_25688' 'TCR_238' 'TCR_29431' 'TCR_46001' 'TCR_2461'
 'TCR_65088' 'TCR_38916' 'TCR_6202' 'TCR_51171' 'TCR_30086' 'TCR_23753'
 'TCR_5483' 'TCR_2993' 'TCR_24875' 'TCR_66064' 'TCR_39082' 'TCR_12925'
 'TCR_39814' 'TCR_37765' 'TCR_62061' 'TCR_52878' 'TCR_21529' 'TCR_19064'
 'TCR_46371' 'TCR_12853' 'TCR_29222' 'TCR_18326' 'TCR_11236' 'TCR_65368'
 'TCR_15410' 'TCR_10556' 'TCR_66215' 'TCR_21346' 'TCR_59205' 'TCR_11883'
 'TCR_19251' 'TCR_16665' 'TCR_52559' 'TCR_4737' 'TCR_38653' 'TCR_2456'
 'TCR_15352' 'TCR_443' 'TCR_23900' 'TCR_45564' 'TCR_51425' 'TCR_61186'
 'TCR_39767' 'TCR_10283' 'TCR_26911' 'TCR_61423' 'TCR_42131' 'TCR_47307'
 'TCR_37588' 'TCR_19805' 'TCR_64034' 'TCR_56577' 'TCR_9708' 'TCR_61551'
 'TCR_27542' 'TCR_2532' 'TCR_24972' 'TCR_65366' 'TCR_4356' 'TCR_37385'
 'TCR_8085' 'TCR_46361' 'TCR_64801' 'TCR_9073' 'TCR_14786' 'TCR_31785'
 'TCR_54238' 'TCR_5900' 'TCR_18947' 'TCR_29186' 'TCR_43031' 'TCR_5816'
 'TCR_16805' 'TCR_462' 'TCR_27862' 'TCR_23035' 'TCR_41056' 'TCR_34948'
 'TCR_48307' 'TCR_29139' 'TCR_59610' 'TCR_14704' 'TCR_61936' 'TCR_11796'
 'TCR_54344' 'TCR_30878' 'TCR_33098' 'TCR_11144' 'TCR_52307' 'TCR_19971'
 'TCR_49720' 'TCR_537' 'TCR_60933' 'TCR_52669']
['TCR_28167' 'TCR_54506' 'TCR_59772' 'TCR_2911' 'TCR_17481' 'TCR_63632'
 'TCR_18913' 'TCR_45784' 'TCR_24236' 'TCR_17593' 'TCR_56787' 'TCR_18659'
 'TCR_50387' 'TCR_51765' 'TCR_13627' 'TCR_20419' 'TCR_57869' 'TCR_40568'
 'TCR_17310' 'TCR_9502' 'TCR_25967' 'TCR_10239' 'TCR_65690' 'TCR_10998'
 'TCR_43344' 'TCR_9581' 'TCR_44818' 'TCR_45229' 'TCR_33390' 'TCR_17646'
 'TCR_44509' 'TCR_64070' 'TCR_15488' 'TCR_63050' 'TCR_35009' 'TCR_4231'
 'TCR_19967' 'TCR_47469' 'TCR_20987' 'TCR_26460' 'TCR_53483' 'TCR_13041'
 'TCR_36946' 'TCR_45828' 'TCR_17955' 'TCR_27760' 'TCR_30698' 'TCR_49990'
 'TCR_8595' 'TCR_60391' 'TCR_21433' 'TCR_11091' 'TCR_13125' 'TCR_45898'
 'TCR_19414' 'TCR_23935' 'TCR_61062' 'TCR_6266' 'TCR_60559' 'TCR_25284'

array(['TCR_65135', 'TCR_24101', 'TCR_28104', ..., 'TCR_63401',
       'TCR_35052', 'TCR_13712'], shape=(13500,), dtype=object)

In [12]:
print(test_tcr)
# array(['TCR_15376', 'TCR_56638', 'TCR_49444', ..., 'TCR_18404',
    #    'TCR_33660', 'TCR_24011'], shape=(20200,), dtype=object)
print(val_tcr)    
# 'TCR_37164' 'TCR_849' 'TCR_55986' ... 'TCR_37826' 'TCR_1864' 'TCR_42771']

not_train_tcr = np.append(val_tcr, test_tcr)

['TCR_15376' 'TCR_56638' 'TCR_49444' ... 'TCR_53494' 'TCR_44475'
 'TCR_43543']
['TCR_65135' 'TCR_24101' 'TCR_28104' ... 'TCR_63401' 'TCR_35052'
 'TCR_13712']

In [13]:
train_tcr = Data_all[~Data_all["TCR_name"].isin(not_train_tcr)]["TCR_name"].value_counts().index
# print(len(train_tcr) + len(val_tcr) + len(test_tcr))

# print(np.sum(np.isin(val_tcr, test_tcr)))
# print(np.sum(np.isin(train_tcr, test_tcr)))
# print(np.sum(np.isin(train_tcr, val_tcr)))
# print(np.sum(np.isin(train_tcr, not_train_tcr)))

print(len(np.unique(np.append(train_tcr, not_train_tcr))))
print(len(Data_all["TCR_name"].value_counts().index))

66957
66957

In [14]:
Train_relations = cmv_dataset[cmv_dataset["TCR_name"].isin(train_tcr)]
Train_relations.reset_index(inplace=True, drop=True)
Validation_relations = cmv_dataset[cmv_dataset["TCR_name"].isin(val_tcr)]
Validation_relations.reset_index(inplace=True, drop=True)
Test_relations = cmv_dataset[cmv_dataset["TCR_name"].isin(test_tcr)]
Test_relations.reset_index(inplace=True, drop=True)
print(Train_relations.shape, Validation_relations.shape, Test_relations.shape, cmv_dataset.shape)

(85588, 9) (23968, 9) (24358, 9) (133914, 9)

In [15]:
Train_relations

,Name,pMHC,CDR3a,CDR3b,Epitop,TCR_name,HLA_MHC,Binding,Count
0,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_100,A0301_KLGGALQAK_IE-1_CMV_binder,CAVRDDDYKLSF,CASRFLAGGSHEQYF,IE-1_CMV_binder,TCR_100,HLA-A0301,0,4
1,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_1000,A0301_KLGGALQAK_IE-1_CMV_binder,CAVRGYSSASKIIF,CASSHTEETGELFF,IE-1_CMV_binder,TCR_1000,HLA-A0301,0,1
2,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_10000,A0301_KLGGALQAK_IE-1_CMV_binder,CALSDPLPLNAGKSTF,CASSERGGTVNEQFF,IE-1_CMV_binder,TCR_10000,HLA-A0301,0,1
3,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_10001,A0301_KLGGALQAK_IE-1_CMV_binder,CALSEAGPDTNAGKSTF,CATSDFGRTGELFF,IE-1_CMV_binder,TCR_10001,HLA-A0301,0,1
4,A0301_KLGGALQAK_IE-1_CMV_binder_TCR_10002,A0301_KLGGALQAK_IE-1_CMV_binder,CALSEAGTNAGKSTF,CASSSVLRAGTLTGANVLTF,IE-1_CMV_binder,TCR_10002,HLA-A0301,0,1
...,...,...,...,...,...,...,...,...,...
85583,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9990,A2402_AYAQKIFKI_IE-1_CMV_binder,CALSEVNYGQNFVF,CSGARWKSSYNEQFF,IE-1_CMV_binder,TCR_9990,HLA-A2402,0,1
85584,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9992,A2402_AYAQKIFKI_IE-1_CMV_binder,CALSEVYGQNFVF,CASNAGTGDYQPQHF,IE-1_CMV_binder,TCR_9992,HLA-A2402,0,1
85585,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9993,A2402_AYAQKIFKI_IE-1_CMV_binder,CALSGDNYGQNFVF,CASSETGTYEQYF,IE-1_CMV_binder,TCR_9993,HLA-A2402,0,1
85586,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9995,A2402_AYAQKIFKI_IE-1_CMV_binder,CALSLDNYGQNFVF,CASSETSLYEQYF,IE-1_CMV_binder,TCR_9995,HLA-A2402,0,1
85587,A2402_AYAQKIFKI_IE-1_CMV_binder_TCR_9999,A2402_AYAQKIFKI_IE-1_CMV_binder,CAANTNAGKSTF,CASRRLATNEKLFF,IE-1_CMV_binder,TCR_9999,HLA-A2402,0,1

In [16]:
Train_relations.to_pickle(train_path)
Validation_relations.to_pickle(val_path)
Test_relations.to_pickle(test_path)